### ISSUE TITLE
SnapshotMetrics.pulse() fails with GraphQL error: Field 'hasCompletedSnapshots' doesn't exist on type 'Site'

### ISSUE THREAD

**Issue by unkhz** [calibreapp/cli#36]
## CLI Installation method

* [x] NPM / NPX
* [ ] Binary

## Output of `calibre --version`

1.1.1

## Operating system

* [x] Mac
* [ ] Windows
* [ ] Linux

## What you expected to happen

I'm using a script based on the `get-all-pulse-metrics.js` which has been working fine. Today the script failed with a GraphQL error.

## What happened
The following GraphQL error is breaking the `SnapshotMetrics.pulse call`
```
[ { message: 'Field \'hasCompletedSnapshots\' doesn\'t exist on type \'Site\'',
    locations: [ [Object] ],
    fields:
     [ 'query GetPulsePageData',
       'organisation',
       'site',
       'hasCompletedSnapshots' ] } ]
```

Removing `hasCompletedSnapshots` field from the query (https://github.com/calibreapp/cli/blob/c89be679ab1a3bd017a3e574b0d9c6ec76823468/src/api/snapshot-metrics.js#L64) seemed to fix the issue.

## Steps to Reproduce (for bugs)

Run the `get-all-pulse-metrics.js` example with valid API token

**Comment by benschwarz** [comment]
Hi @unkhz ! 

Thanks for logging this - We had a release that had some unforeseen errors with the calculation of `hasCompletedSnapshots`. We've since identified and fixed the issue. 

We're no longer seeing the issue from our issue tracking, so I'm closing this issue for now. If you have any troubles at all, please don't hesitate to comment here or contact support for a hand!
