### ISSUE TITLE
Allow calling api from the client-side

### ISSUE THREAD

**Issue by phenax** [calibreapp/cli#39]
Can we enable calling the api from the client-side?

My first approach was to try to use the node api as graphql-request works for both node and js. This didn't work as it expected a CALIBRE_API_TOKEN. The entire api takes input as environment variables.

If the node api could be refactored to allow passing those values it would make for a cleaner and more flexible api. If that's not feasible, can the graphql api be tweaked such that it works for cross origin requests?
I tried calling the graphql api directly but currently when I call the api from the client-side, the network request fails as newer browsers makes a pre-flight OPTIONS request which throws a 404.

**Comment by benschwarz** [comment]
Hey @phenax, thanks for writing in!

It seems like there are two problems stopping you from being able to use `calibre` in the browser: 

1. `CALIBRE_API_TOKEN` can only be passed in via ENV vars
2. The API does not have CORS headers 

The CLI / Node.js API was definitely not built with browser-js in mind, would you be able to explain what you're planning on building with this? It'd be good to understand a little bit more context before we make changes there. We're not adverse to making some changes to support it, but some more information would be great 👍 (If you'd prefer to do that privately, let's chat via support)

**Comment by phenax** [comment]
@benschwarz  I dont have something specific in mind but the intention was to have a way to show custom visualizations and an exportable datasheet of metrics as a webapp. I could create a new server for making the api calls but it doesnt seem like a case where I should need one.

**Comment by benschwarz** [comment]
@phenax we just released CLI 1.2.0, which exposes Calibre's GraphQL API so that you can make abstract queries. I know that's not exactly what you were looking for, but it might prove valuable all the same. 

At this stage, I'd recommend exposing the API through a small Node.js app that is able to securely hold your `CALIBRE_API_TOKEN`, running requests through that. (Using either the Node.js API, or GraphQL).

I'm going to close the issue for now, but if you have any other questions, ideas or thoughts please do share them.
